config/routes.rb
Rails.application.routes.draw do

 resources :canvas
 resources :tasks

  root 'pages#home'
  

end

app/models/canva.rb
# == Schema Information
#
# Table name: canvas
#
#  id            :integer          not null, primary key
#  title         :string
#  description   :text
#  collaborators :string
#  timeline      :string
#  budget        :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Canva < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  canvas_id   :integer
#  title       :string
#  description :text
#  priority    :string
#  deadline    :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Task < ActiveRecord::Base
  belongs_to :canva
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/canvas_controller.rb
class CanvasController < ApplicationController
# kind of redundant 

   def create 
    @canva = Canva.new(canva_attributes)
    render json: {title: @canva.title, description: @canva.description, collaborators: @canva.collaborators, timeline: @canva.timeline, budget: @canva.budget}
    end 

  private

  def canva_attributes
    params.require(:canva).permit(:title, :description, :collaborators, :timeline, :budget)
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home 
    @canva = Canva.new
    @task = Task.new
  end
  
  def new 
    @canva = Canva.new
  end

  def create 
   
  end

  def index
    @canva = Canva.new
  end

  def show 
    @canva = Canva.find(params[:id])
    render 'pages'
  end

  def update
  end

  def destroy
    @canva = Canva.find(params[:id])
  end

  private

  def canva_attributes
    params.require(:canva).permit(:title)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end
  
  def create 
    @task = Task.new
  end 

  private 

  def 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canvas_helper.rb
module CanvasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/canvas/index.html.erb
<div class="conatiner">
<h1>Canvas</h1>
    <%= form_for @canva do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :collaborators %>
    <%= f.text_field :collaborators %>
    <%= f.label :budet %>
    <%= f.text_field :budget %>
    <%= f.label :timeline %>
    <%= f.text_field :timeline %>
    <%= f.submit "(+) Create Canvas" %>
    <% end %>

  </div>

app/views/canvas/new.html.erb
<div class="conatiner">
<h1>Canvas</h1>
    <%= form_for @canva do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <%= f.label :collaborators %>
    <%= f.text_field :collaborators %>
    <%= f.label :budet %>
    <%= f.text_field :budget %>
    <%= f.label :timeline %>
    <%= f.text_field :timeline %>
    <%= f.submit "(+) Create Canvas" %>
    <% end %>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Canvas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Canvas</title>
</head>

<body>
  <div class="container">
   <h1>Canvas</h1>
   <p><i>A Trello Board for Creatives</i>
   
   <div class="canvas_form"> 
     <h2>Canvas</h2>
      <%= form_for(@canva, url: canvas_path, html:{method: :post})do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title, :placeholder => "ex. Jeff Koons Sculpture" %> <br>
      <%= f.label :description %>
      <%= f.text_area :description %><br>
      <%= f.label :collaborators %>
      <%= f.text_field :collaborators %><br>
      <%= f.label :budet %>
      <%= f.text_field :budget %><br>
      <%= f.label :timeline %>
      <%= f.text_field :timeline %><br>
      <%= f.submit id:"canva_submit", value:"(+) Create Canvas" %>
      <% end %>
    </div>
    <div class="canvas">

    <!-- where you will render new canvas-->
    </div>

    <div class="tasks_form"> 
    <h2>New Task</h2>
    <%= form_for @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :description %>
    <%= f.text_area :description %><br>
    <%= f.submit %>
    <% end %>
  </div><!-- #wrapper -->
</body>
</html>

app/views/tasks/new.html.erb
 <div class="row"> 
    <h2>New Task</h2>
    <%= form_for @task do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :description %>
    <%= f.text_area :description %><br>
    <%= f.submit "(+) Save" %>
    <% end %>
  </div>